added clipShapeOnSave parameter
icapps/flutter-custom-image-crop pull request #29
Opened 2023-08-05 02:46 UTC by g0dzillaa

Currently the app will clip the area outside of the Circle when we use the Circle shape. This is a problem if we only want to show the Circle shape but save the Rectangle shape in the server.

For example, if we want to show the avatar in circle shape and in the future if they want to show it in rectangle or need a rectangle image somewhere else in the platform, they cannot get it now as we are clipping the area outside of the circle.

`clipShapeOnSave` param allows us to save the image file in Rectangle path so that we can have the flexibility of changing the shape in the future. By default, the `clipShapeOnSave` is set to false.

2023-08-07 20:11 UTC, ikbendewilliam requested changes
Thank you for your PR! Just one small issue and formatting.

2023-08-07 20:11 UTC, ikbendewilliam commented on lib/src/widgets/custom_image_crop_widget.dart
>          return Path()
formatting, please use `dart format .`

2023-08-07 20:11 UTC, ikbendewilliam commented on lib/src/widgets/custom_image_crop_widget.dart
>          return Path()
I would also do the check to clip before the `switch`. This way if we add more shapes, you don't need to add the clip everywhere

2023-08-26 14:34 UTC, closed without merging

2023-08-26 14:35 UTC, g0dzillaa commented
Closing this one as I mixed up some local files and too much hassle to fix it. Will open another PR.