optimize fillcropscpace imagefit
icapps/flutter-custom-image-crop pull request #45
Opened 2023-09-19 05:09 UTC by YumengNevix

1. ensure crop area will not move out image
2. ensure croped image has no white border

2023-10-03 06:49 UTC, ikbendewilliam commented
Works pretty good, one issue I see is that if you zoom out and then in, its not allowed.

2023-10-03 06:54 UTC, ikbendewilliam requested changes

2023-10-03 06:54 UTC, ikbendewilliam commented on lib/src/widgets/custom_image_crop_widget.dart
> +    if (_imageAsUIImage == null ||
Also add an option in the widget `forceInsideCropArea` and disable it by default so it's not a breaking change + there is no unexpected behaviour.

2023-10-03 06:54 UTC, ikbendewilliam commented on lib/src/widgets/custom_image_crop_widget.dart
> +    if (_imageAsUIImage == null ||
Also add this argument/property to the readme

2023-10-16 03:13 UTC, YumengNevix commented
> Works pretty good, one issue I see is that if you zoom out and then in, its not allowed.

Pre implementation only support angle which is integer multiple of pi/2,  latest commit supports any angle, so this issue should be fixed.

2023-10-17 07:49 UTC, ikbendewilliam commented
Some great work already!
The angle wasn't the issue, previously if I zoomed out using the buttons everything was good, then zooming in with the buttons would result in a zoom level of `0,9975` which didn't work (1.33 x 0.75), I guess that was on the numbers I used, if we used 1.34 it would have worked. 
That being said, the zoom buttons now don't work at all now when this is enabled (unless I first zoom out with gestures), which is a bigger issue. 
Also if I turn left once, then turn right once (using the buttons), the image is zoomed out.

2023-10-17 10:00 UTC, YumengNevix commented
> Some great work already! The angle wasn't the issue, previously if I zoomed out using the buttons everything was good, then zooming in with the buttons would result in a zoom level of `0,9975` which didn't work (1.33 x 0.75), I guess that was on the numbers I used, if we used 1.34 it would have worked. That being said, the zoom buttons now don't work at all now when this is enabled (unless I first zoom out with gestures), which is a bigger issue. Also if I turn left once, then turn right once (using the buttons), the image is zoomed out.

1.  The zoom out bug is caused by _getDistanceBetweenPointAndLine, it may result in NaN，so I prevent the scale op.
2. The zoom in bug is caused by _calculateScaleAfterRotate, when data.scale is less than 1.0, startScale is 1.33, endScale is 1.4, binary search range should be [data.scale, endScale] rather than [startScale, endScale], after modify implementation, it will result in 1.0 rather than 1.33.
3. When user rotate, scale will change automatically to ensure fully cover path, it's by design, not bug.

2023-10-26 06:36 UTC, ikbendewilliam commented
Works great! Thank you!

2023-10-26 06:36 UTC, merged

2023-10-26 06:46 UTC, ikbendewilliam commented
released in 0.0.13